### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by Mamelukki** [mremes/tsoha-rankkauslista#6]
Projekti ladattu torstaina 18.10. klo 11.25. 

Sovellus näyttää selkeältä ja siinä on paljon ominaisuuksia ja toimintoja, hyvä! 

Näinkin ohjelman toimintaa jonkin verran jo demotilaisuudessa, mutta testailin sovellusta itse jonkin aikaa eri rooleilla ja havaitsin seuraavanlaisia epäkohtia: 

- Pelaajien tietojen muokkauslomakkeessa on sukupuoli-kohdassa sekä yksittäinen kenttä että monivalintakenttä päällekäin, joten toisen kentän voisi ottaa pois.

- Yritin luoda ranking-listan nimellä “Lista”, mutta sain virheilmoituksen “Nimen pitää olla vähintään 2 ja enintään 60 merkkiä pitkä.”. Alaraja taitaa todellisuudessa olla 6 merkkiä?

- Kuten demotilaisuudessa kävikin ilmi, roolit eivät toimi oikein. Pystyn esimerkiksi pelaajana luomaan itse ranking-listan. Pelaajana järjestelmään kirjautunut pystyy myös lisäämään useita pelaajia järjestelmään - toisin sanoen muitakin pelaajia kuin vain itsensä. 

- Pelaajan syntymäajaksi voi laittaa esimerkiksi vuoden 1000, mikä ei ehkä ole kovin mielekästä. 

- Pelaajan voi yrittää laittaa samalle ranking-listalle useamman kerran. Olisiko tässä mahdollista antaa esimerkiksi virheilmoitus, joka kertoo, että pelaaja on jo kyseisellä listalla?

- Sovelluksen käyttöä saattaisi jonkin verran helpottaa paluu-napit. Jos klikkaan esimerkiksi tyhjän ranking-listan auki, en voi tehdä sivulla mitään enkä voi palata takaisin edelliselle sivulle muuten kuin klikkaamalla taas Etusivu-linkkiä tai selaimen paluu-nappia. 

- Turnauksien tietoja ei saa auki ainakaan nimeä klikkaamalla, enkä löytänyt tähän muutakaan reittiä. Onko tämä tarkoituksellista? Turnauksen luonti on myös mahdollista “jättää kesken” ja silti turnaus löytyy etusivulta. En esimerkiksi lisännyt ollenkaan palkintoja, mutta sovellus ilmoittaa, että palkinnot on silti luotu ja turnauksen tiedot ilmestyvät etusivulle. Turnaus näkyy etusivulla myös esimerkiksi silloin, kun en edes siirry luontivaiheessa palkinnot-kohtaan.  

- Kun ranking-listan kautta avaa pelaajan tiedot, on ehkä vähän hämmentävää, että esimerkiksi “Poista pelaaja” ei poistakaan pelaajaa pelkästään listalta, vaan se poistaa myös koko pelaajan. Onko ranking-listaa edes mahdollista muokata?

- En myöskään ihan ymmärrä, mistä pelaajien pisteet tulevat. En saanut kenellekään lisättyä pisteitä, vaikka osa pelaajista oli osallistunut turnauksiin. 

Kokonaisuudessaan sovellus toimii kyllä hyvin, koodi on siistiä ja esimerkiksi etusivulla olevat listaukset näyttävät selkeiltä ja listaavat kaiken oleellisen. Hakemistorakenne voisi ehkä olla yksityiskohtaisempi eli esimerkiksi templates-kansion sisällä olisi vielä pienempiä alikansioita eri kokonaisuuksille - se helpottaisi sovelluksen hahmottamista. Myös asennusohjetta voisi monipuolistaa, mutta dokumentaatio on muuten varsin kattavaa. Hyvää työtä! :)

**Comment by mremes** [comment]
Kiitos palautteestasi! Siitä oli hyötyä työn viimeistelyssä :)
